title: Sysadmin Guide
logo: /assets/img/avatar.png
description: My personal system administrator guide.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

<style type="assets/css/style.scss">
  h1.title {
    text-align: center;
  }
}
</style>
