title: Sysadmin Guide
logo: /assets/img/avatar.png
description: My personal system administrator guide. Informations provided on this website may be inaccurate or incomplete. Always consult official sources.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
