---

- hosts: all
  become: true
  tasks:
  - name: install apache and php packages
    package:
      name:
        - "{{ apache_package_name }}"
        - "{{ php_package_name }}"
      state: latest
      update_cache: yes

- hosts: centos
  become: true
  roles:
    - centos
