---

- hosts: all
  become: true
  tasks:
  - name: install httpd package
    package:
      name: httpd
      state: latest
      update_cache: yes

  - name: start httpd service
    service:
      name: httpd
      state: started
      enabled: yes 

  - name: add https firewall rule
    ansible.posix.firewalld:
      service: https
      permanent: true
      state: enabled

  - name: add http firewall rule
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled

  - name: restart service httpd, in all cases
    service:
      name: httpd
      state: restarted

  - name: reload firewall service, in all cases
    service:
      name: firewalld
      state: restarted

