---

- hosts: all
  become: true
  tasks:
  - name: install updates (CentOS)
    ansible.builtin.yum:
      name: '*'
      state: latest
    when: ansible_distribution == "CentOS"
  - name: install updates (CentOS)
    ansible.builtin.apt:
      name: '*'
      state: latest
    when: ansible_distribution == "Ubuntu"
